(function(_ds){var window=this;var fEa=function(){return(0,_ds.O)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},gEa=function(){return(0,_ds.O)('<div class="devsite-book-nav-blur"></div>')},hEa=function(a){a=a.eN;a=_ds.RI(new _ds.Jt("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.tw(_ds.ns(1)),XXX_2:_ds.tw(_ds.ns(a))});return(0,_ds.O)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var iEa="onpointerover"in window?"pointerover":"mouseover",AT=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.wk(a,"visually-hidden","",c))},jEa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;a.eventHandler.Mb(a,_ds.Bl,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.wk(a,"animatable","");b=_ds.Of(a.oa`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.wk(a,"aria-label","Hide side navigation",a.j),_ds.wk(a,"data-title","Hide side navigation",a.j),a.removeAttribute("collapsed"),_ds.Ct(a.j,"expanded","true"),BT(a,"expandedLeftNav","Expanded book nav","click")):(_ds.wk(a,
"aria-label","Show side navigation",a.j),_ds.wk(a,"data-title","Show side navigation",a.j),_ds.wk(a,"collapsed",""),_ds.Ct(a.j,"expanded","false"),BT(a,"collapsedLeftNav","Collapsed book nav","click"),a.eventHandler.Mb(a,_ds.Bl,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.am();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},kEa=function(a){a.eventHandler.listen(a,"click",b=>{const c=CT(a,b.target);c&&BT(a,
"click",`Book nav link, pathname: ${c.href}`,void 0,{eventDetail:c.href});DT(a,b)});a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&DT(a,b)});a.eventHandler.listen(a,[iEa,"focusin"],b=>{b.defaultPrevented||(b=CT(a,b.target))&&_ds.Ef(b,_ds.Vl(b.href).href)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(ET(a,"_book")?a.removeAttribute("top-level-nav"):_ds.wk(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.va.cb());a.eventHandler.listen(a,
"devsite-content-updated",()=>{a.va.cb()});a.eventHandler.listen(a,"scroll",()=>{_ds.wk(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Fa.cb()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.Aa.cb()),a.eventHandler.listen(a.m,"focus",()=>void FT(a,"focus")));a.ra&&a.eventHandler.listen(a.ra,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.ra)==null||c.classList.add("hidden");GT(a);HT(a);FT(a,b.type)}})},
IT=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.qa=new Set(b);if(!_ds.E().hash&&c)lEa(a,a.qa);else{c=new _ds.lM;for(const d of a.qa)_ds.kM(c,d)}},JT=async function(a){const b=await _ds.x();for(const c of a.qa)b.unregisterIntersectionForElement(c)},CT=function(a,b){b=_ds.xl(b,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0);return b===a?null:b},BT=function(a,b,c,d,e){a.Da(Object.assign({},{category:"Site-Wide Custom Events",action:d||b},c&&{label:c}));
b=Object.assign({},{type:"bookNav",name:b},e&&{metadata:e});a.dispatchEvent(_ds.kf(b))},DT=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.wk(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&ET(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=
c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.wk(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||
(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},FT=function(a,b){BT(a,b==="focus"?"filterInput":"filterClearButton",b==="focus"?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button",b)},KT=function(a){a.xa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},
MT=function(a){const b=_ds.E().searchParams.get("nf");a.m&&b&&(a.m.value=b,LT(a))},LT=function(a){if(a.xa.length){GT(a);HT(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:c.trim().toLowerCase();if(d){var e;(e=a.ra)==null||e.classList.remove("hidden");for(const g of a.xa){var f=g.querySelectorAll(".devsite-nav-text");a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:
[]).some(q=>q.toLowerCase().includes(d));let n,p;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(p=n.textContent)==null?0:p.toLowerCase().includes(d))))e=c=!0;else for(const q of f){let t,w,y,I;f=((I=(t=q)==null?void 0:(w=t.parentElement)==null?void 0:(y=w.getAttribute("data-synonyms"))==null?void 0:y.split(","))!=null?I:[]).some(G=>G.toLowerCase().includes(d));if(d){let G;if(f||((G=q.textContent)==null?0:G.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");
if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const q of c){q.classList.remove("hidden");let t,w,y,I;c=((I=(t=q)==null?void 0:(w=t.parentElement)==null?void 0:(y=w.getAttribute("data-synonyms"))==null?void 0:y.split(","))!=null?I:[]).some(K=>K.toLowerCase().includes(d));let G;d&&(c||((G=q.textContent)==null?0:G.toLowerCase().includes(d)))&&++b}}mEa(g,d)}a&&b>0&&nEa(g,b)}}else(f=a.ra)==null||f.classList.add("hidden")}},GT=function(a){for(const b of a.xa){let c;b.classList.toggle("hidden",
!((c=a.m)==null||!c.value))}},HT=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a)a=c.parentElement,b=a==null?void 0:a.textContent,a&&b&&_ds.Mf(a,_ds.ig(b))}},mEa=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.Mf(a,
_ds.ig(d))}},nEa=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.qq(hEa,{eN:b}),a.appendChild(b)},lEa=async function(a,b){if(a.connected){var c=await _ds.x(),d=new _ds.lM,e=f=>{f=f.target;_ds.kM(d,f);a.qa.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},ET=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.wk(a,
"hidden","",d);return c},NT=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.fm(_ds.E().pathname);a=`[href="${_ds.Vl(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.Ct(c,"current","page")},OT=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},oEa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.am(),await PT(a),await a.ya,
await _ds.x(),await _ds.am(),await PT(a))},PT=async function(a){if(a.connected&&a.o){await _ds.x();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await pEa(a,b))}},pEa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Kn(b,a,!0).y;await _ds.am();c&&_ds.wk(a,"user-scrolled","")}},QT=class extends _ds.zk{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.ra=this.m=
this.ua=this.o=null;this.xa=[];this.eventHandler=new _ds.v;this.Ba=()=>{};this.qa=new Set;_ds.vk(this,this.oa`animatable`,this.oa`aria-expanded`,this.oa`aria-label`,this.oa`collapsed`,this.oa`data-title`,this.oa`fixed`,this.oa`has-book-nav`,this.oa`hidden`,this.oa`top-level-nav`,this.oa`user-scrolled`,this.oa`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.qq(fEa);this.ea=_ds.qq(gEa);this.ya=new Promise(a=>{this.Ba=a});
this.va=new _ds.qh(()=>{this.connected&&AT(this)},20);this.Aa=new _ds.qh(()=>{LT(this)},20);this.Fa=new _ds.qh(()=>{jEa(this)},100)}async connectedCallback(){this.connected=!0;_ds.fl(this.background,this);this.hasAttribute("hidden")&&(_ds.wk(this,"hidden","",this.j),_ds.wk(this,"hidden","",this.ea));let a;(a=this.parentElement)==null||a.insertBefore(this.j,this.nextSibling);_ds.wk(this,"aria-label","Hide side navigation",this.j);_ds.wk(this,"data-title","Hide side navigation",this.j);_ds.wk(this,
"aria-expanded","true",this.j);let b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ua=this.querySelector(".devsite-book-nav-filter"))this.m=this.ua.querySelector("input[type=text]"),this.ra=this.ua.querySelector(".filter-clear-button"),KT(this),MT(this);AT(this);kEa(this);await this.init();IT(this)}disconnectedCallback(){this.connected=!1;this.eventHandler.removeAll();JT(this);this.qa.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.wk(this,"visually-hidden",
"",a);a=[this.background,this.j,this.ea];for(const b of a)b&&_ds.hl(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");
b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.wk(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.j,this.ea];for(const d of c)d&&(b?_ds.wk(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.Ba()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");
_ds.wk(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.wk(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.wk(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(NT(this),OT(this),await oEa(this)):(await _ds.am(),await PT(this))}}async xd(a){a?(a=a.querySelector("nav")||null,NT(this,a),OT(this,a),a&&(await JT(this),this.qa.clear(),IT(this,a,
!1)),_ds.yk(this,this.querySelector("nav"),a)):_ds.el(this);KT(this);if(this.m){this.m.value="";let b;(b=this.ra)==null||b.classList.add("hidden");MT(this)}await _ds.am();await this.init(!1)}};QT.prototype.updateContent=QT.prototype.xd;QT.prototype.attributeChangedCallback=QT.prototype.attributeChangedCallback;QT.prototype.disconnectedCallback=QT.prototype.disconnectedCallback;QT.prototype.connectedCallback=QT.prototype.connectedCallback;try{customElements.define("devsite-book-nav",QT)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
