#!/bin/zsh
# ============================================================
# M2 ULTRA — DOWNLOADS TRIAGE SCRIPT
# Surfaces all NOIZY-related critical files from ~/Downloads
# RSP_001 | GOD.local | 2026-03-24
# ============================================================

DOWNLOADS="$HOME/Downloads"
OUTPUT="$HOME/NOIZYLAB/_triage_downloads_$(date +%Y%m%d_%H%M%S).md"

echo "# Downloads Triage Report — $(date)" > "$OUTPUT"
echo "_Generated by triage_downloads.sh on GOD.local_\n" >> "$OUTPUT"

echo "## 🔍 NOIZY Files Found\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -iname "*noizy*" -o -iname "*gabriel*" -o -iname "*heaven*" -o -iname "*hvs*" -o -iname "*dreamchamber*" -o -iname "*RSP*" 2>/dev/null | sort >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## 📜 Shell Scripts Found\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -name "*.sh" -o -name "*.command" 2>/dev/null | sort >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## ⚛️ React/JSX Components Found\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -name "*.jsx" -o -name "*.tsx" 2>/dev/null | sort >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## 📝 Markdown Files Found\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -name "*.md" 2>/dev/null | sort >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## 🌐 HTML Files Found\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -name "*.html" 2>/dev/null | sort >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## 📦 Largest Files (Top 30)\n\`\`\`" >> "$OUTPUT"
find "$DOWNLOADS" -type f 2>/dev/null -exec du -sh {} \; 2>/dev/null | sort -hr | head -30 >> "$OUTPUT"
echo "\`\`\`\n" >> "$OUTPUT"

echo "## 📊 Size by Subfolder\n\`\`\`" >> "$OUTPUT"
du -sh "$DOWNLOADS"/*/ 2>/dev/null | sort -hr >> "$OUTPUT"
echo "\`\`\`" >> "$OUTPUT"

echo "✅ Triage complete. Report saved to:"
echo "   $OUTPUT"
open "$OUTPUT" 2>/dev/null || cat "$OUTPUT"
