#!/usr/bin/env bash
set -euo pipefail

# EDGE CORE: Automatic Public Postmortem Template Generator
# Generates a public-safe postmortem draft on zone migration failure
# Facts only, no speculation, no blame language

POSTMORTEM_DIR="/Users/m2ultra/NOIZYANTHROPIC/postmortems"
mkdir -p "$POSTMORTEM_DIR"

TS=$(date -Iseconds)
DATE=$(date +%Y-%m-%d)
FILENAME="zone-migration-${DATE}.md"
FILEPATH="${POSTMORTEM_DIR}/${FILENAME}"

# Gather context from environment (set by CI or calling script)
MIGRATION_STATUS="${MIGRATION_STATUS:-unknown}"
DETECTION_METHOD="${DETECTION_METHOD:-EDGE CORE automated checks}"
IMPACT_DURATION="${IMPACT_DURATION:-No sustained outage}"
ROOT_CAUSE="${ROOT_CAUSE:-Under investigation}"
PAGERDUTY_INCIDENT="${PD_INCIDENT_URL:-None}"

cat > "$FILEPATH" <<EOF
# Postmortem: noizy.ai Zone Migration

**Date:** ${DATE}
**Generated:** ${TS}
**Status:** Draft (Public-Safe)
**Classification:** Infrastructure

---

## Summary

A planned zone migration for \`noizy.ai\` did not complete successfully.
Automated safeguards halted progression before sustained user impact.

---

## Timeline

| Time | Event |
|------|-------|
| T-0 | Migration initiated |
| T+X | Anomaly detected by ${DETECTION_METHOD} |
| T+X | Migration automatically halted |
| T+X | Rollback initiated |
| T+X | Service stability confirmed |

*Exact timestamps to be filled in after review.*

---

## What Happened

- Migration intent was validated via EDGE CORE governance
- Prerequisites were verified (KV created, Worker deployed, route tested)
- During migration execution, an inconsistency was detected
- EDGE CORE safeguards automatically blocked progression
- No changes were committed to production DNS

---

## Impact

- **User-facing:** ${IMPACT_DURATION}
- **Data integrity:** No loss of creator data
- **Trust surface:** No consent or provenance compromise
- **Financial:** No billing impact

---

## Detection

- **Primary:** ${DETECTION_METHOD}
- **Secondary:** PagerDuty alerting
- **Incident:** ${PAGERDUTY_INCIDENT}

The detection was **proactive** (before user impact), not reactive.

---

## Response

1. Migration automatically halted by EdgeGovernor DRM token validation
2. Zone ownership remained with source account
3. DNS records unchanged
4. SSL/TLS certificates unchanged
5. DNSSEC status unchanged
6. Service continued operating normally

---

## Root Cause

${ROOT_CAUSE}

*This section will be updated after technical review.*

---

## Resolution

The migration was safely rolled back before completion.
A new migration window will be scheduled only after:

- [ ] Root cause identified
- [ ] Additional safeguards implemented (if needed)
- [ ] Verification procedures enhanced
- [ ] Team review completed

---

## Preventive Measures

### Already in Place (Worked as Designed)
- EDGE CORE zone migration gate
- EdgeGovernor DRM token requirement
- Pre-migration validation script
- CI prerequisite checks

### To Be Added
- *To be determined after root cause analysis*

---

## Lessons Learned

### What Went Well
- Automated safeguards detected the issue before impact
- Rollback was clean and immediate
- No manual intervention required for recovery
- Incident was contained to infrastructure team

### What Could Be Improved
- *To be determined after review*

---

## Action Items

| ID | Action | Owner | Due | Status |
|----|--------|-------|-----|--------|
| 1 | Complete root cause analysis | TBD | TBD | Open |
| 2 | Update this postmortem with findings | TBD | TBD | Open |
| 3 | Schedule follow-up migration window | TBD | TBD | Open |
| 4 | Publish final postmortem | TBD | TBD | Open |

---

## Appendix

### Related Documents
- [Zone Migration Runbook](../docs/ZONE_MIGRATION_RUNBOOK.md)
- [EDGE CORE Promotion Policy](../docs/EDGE_CORE_PROMOTION_POLICY.md)
- [DR Playbook](../docs/DR-PLAYBOOK.md)

### Audit Trail
- Migration DRM token: \`[REDACTED]\`
- CI run: \`${GITHUB_RUN_URL:-N/A}\`
- Operator: \`${GITHUB_ACTOR:-N/A}\`

---

*This document was auto-generated by EDGE CORE postmortem tooling.*
*It contains only facts suitable for public disclosure.*
*Human review is required before publication.*

---

**Review Checklist:**
- [ ] Timeline accurate
- [ ] Impact assessment correct
- [ ] No internal details exposed
- [ ] No blame language
- [ ] Action items assigned
- [ ] Approved for publication
EOF

echo "✅ Postmortem draft generated: ${FILEPATH}"
echo ""
echo "Next steps:"
echo "  1. Review and fill in timeline details"
echo "  2. Complete root cause analysis"
echo "  3. Assign action items"
echo "  4. Get approval for publication"
echo "  5. Publish to status page / blog"
